# Generated by Django 6.0.6 on 2026-06-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя покупателя')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='new', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
